### ISSUE TITLE
Error while running the command "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by ashokrayal** [pveller/adventureworks-moltin#2]
![error_node_chatbot_25062](https://user-images.githubusercontent.com/26453959/27514541-9b14ccf4-59ab-11e7-9255-ac56ece56ca3.PNG)

**Comment by pveller** [comment]
Can you please show me the script you're running? I see that it's failing to authenticate but I can't diagnose by just looking at the image alone, sorry.

You did set the environment variables, correct? Did the script generate any output before failing?

**Comment by ashokrayal** [comment]
Now It's working. Maybe the issue was occurring because of notwork problem. Thanks
