### ISSUE TITLE
Adventure Works 2014 OLTP Script

### ISSUE THREAD

**Issue by swirjawan** [pveller/adventureworks-moltin#5]
First of all, thank you for the knowledge; I am just learning moltin and chatbot

Anyway, I could not find Adventure Works 2014 OLTP Script anymore, could you please share if you still have it? 

Another thing is that, when i run the current/latest Adventure Works OLTP Script (https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks-oltp-install-script.zip)

I got error:

`Importing products
Creating a product variation color
{ errors:
   [ { title: 'Failed Validation',
       detail: 'The selected data.type is invalid.' } ] }`

Any help would be appreciated

Thanks

**Comment by pveller** [comment]
They moves them to [github](https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks). Try this one: https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks-oltp-install-script.zip. I will update the README

**Comment by swirjawan** [comment]
Manage to get it up and running, thanks for the help 👍
